name: json_schema
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-75.1.beta

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides: 
